---
title: "Research Topic"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(gganimate)
library(plotly)
library(tibble)
```

Introduction {.tabset}
======================

Column {data-width=700}
-----------------------------------------------------------------------

### Chart A

```{r}

```



Column {data-width=300}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Group info

**Team of Thrones**

*Members:*

- *Ambalika Gupta*
- *Smriti Vinayak Bhat*
- *Yin Shan Ho*

Skills {.tabset} 
======================

Column
--------------------------

### Trend of skill categories across the different verticals by year

```{r read-data}
skills_dataset <- readxl::read_excel("../data/public_use-industry-skills-needs.xlsx", sheet = "Industry Skills Needs")
```

```{r}
skill_categ_trend <- skills_dataset %>%
  select(year, skill_group_category, isic_section_name) %>%
  group_by(year,isic_section_name,skill_group_category) %>%
  tally()

skill_categ_trend$skill_group_category = str_wrap(skill_categ_trend$skill_group_category, width = 10)

```

```{r}
cp <- coord_polar(theta='x',start=0,direction=-1)
cp$is_free <- function() TRUE

p <- skill_categ_trend %>%
   ggplot(aes(x = skill_group_category, y = n, fill = skill_group_category)) +
   geom_bar(stat = "identity", width = 1) +
   facet_wrap(~isic_section_name,ncol = 2, labeller = labeller(isic_section_name = label_wrap_gen(30)), scales = "free") +
   coord_flip() +
   theme_bw(base_size = 12) +
   theme(strip.text = element_text(size = 11, colour = "black"),
         strip.background = element_blank(),
         axis.title.y = element_blank(),
         axis.title.x = element_blank(),
         axis.text.y = element_blank(),
         axis.text.x = element_text(size=6,hjust = -1),
         axis.ticks = element_blank(),
         plot.background = element_rect(fill = "transparent", colour = NA),
         panel.border = element_blank(),
    legend.position = 'none',
    aspect.ratio = 1) +
  cp

 p <- p +
   labs(title = 'Year: {round(frame_time)}') +
   transition_time(year)
 animate(p,height = 10, width = 7, units = "in", res = 150)


```


Column
--------------------------

### Trend in change of useful skills across occupations

```{r}
tech_trend <- skills_dataset %>%
  select(year,skill_group_name) %>%
  group_by(year,skill_group_name) %>%
  tally() %>%
  group_by(year) %>%
  arrange(desc(n), .by_group = TRUE)

tech_trend <- by(tech_trend, tech_trend["year"], head, n=10)
tech_trend <- Reduce(rbind,tech_trend)

plot_ly(tech_trend) %>%
  add_bars(
    x = ~year, y = ~abs(n),
    frame = ~year, 
    color = ~skill_group_name,
    line = list(simplify = FALSE)
  ) %>%
  layout(yaxis = list(title = "Skills trend"))
```



### Analysis


Talent Migration {.tabset} 
======================




Employment Growth {.tabset} 
======================



References {.tabset}
======================

World Bank. (n.d.). Skills | LinkedIn Data | Data Catalog. Retrieved May 17, 2021, from https://datacatalog.worldbank.org/dataset/skills-linkedin-data
