---
title: "Cleaning data"
author: "Team_of_Thrones"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(tidyr)
```

# Research Topic


## Skills 

*Researcher: Smriti Vinayak Bhat*

```{r}

```




## Talent Migration

*Researcher: Ambalika Gupta*


```{r}
talent_migration_country <- read_excel("../data/public_use-talent-migration.xlsx", sheet = "Country Migration")
talent_migration_skill <- read_excel("../data/public_use-talent-migration.xlsx", sheet = "Skill Migration")
talent_migration_industry <- read_excel("../data/public_use-talent-migration.xlsx", sheet = "Industry Migration")

```

```{r}
talent_migration_country <- talent_migration_country %>% 
  pivot_longer(cols = c('net_per_10K_2015':'net_per_10K_2019'), names_to = "Year", values_to = "Net_Migration")

talent_migration_skill <- talent_migration_skill %>% 
  pivot_longer(cols = c(net_per_10K_2015:net_per_10K_2019), names_to = "Year", values_to = "Net_Migration")

talent_migration_country <- separate(talent_migration_country, Year, into = c("A", "B", "C", "Year"), sep = "_")

talent_migration_skill <- separate(talent_migration_skill, Year, into = c("A", "B", "C", "Year"), sep = "_")

talent_migration_country <- talent_migration_country %>% 
  select(-A, -B, -C) %>% 
  mutate(Year = as.numeric(Year))

talent_migration_skill <- talent_migration_skill %>% 
  select(-A, -B, -C) %>% 
  mutate(Year = as.numeric(Year))

write.csv(talent_migration_country, "../clean_data/talent_migration_country.csv")

write.csv(talent_migration_skill , "../clean_data/talent_migration_skill.csv")

talent_migration_industry <- talent_migration_industry %>% 
  pivot_longer(cols = c(net_per_10K_2015:net_per_10K_2019), names_to = "Year", values_to = "Net_Migration")

talent_migration_industry <- separate(talent_migration_industry, Year, into = c("A", "B", "C", "Year"), sep = "_")

talent_migration_industry <- talent_migration_industry %>% 
  select(-A, -B, -C) %>% 
  mutate(Year = as.numeric(Year))

write.csv(talent_migration_industry, "../clean_data/talent_migration_industry.csv")






```




## Employment Growth 

*Researcher: Yin Shan Ho*

```{r}
#import data
emp_growth_raw <- read_excel("../data/public_use-industry-employment-growth.xlsx", 
    sheet = "Growth from Industry Transition")
```

```{r}
# clean data
emp_growth <- emp_growth_raw %>% 
  rename( "2015" = growth_rate_2015, 
          "2016" = growth_rate_2016, 
          "2017" = growth_rate_2017, 
          "2018" = growth_rate_2018, 
          "2019" = growth_rate_2019) 

write_excel_csv(emp_growth, "../clean_data/emp_growth.csv")

```


