---
title: "Analysis of Employment Trends"
author: "Smriti Vinayak Bhat, Yin Shan Ho, Ambalika Gupta"
date: "28/05/2021"
bibliography: references.bib
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    number_sections: yes
    citation_package: biblatex
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(plotly)
library(kableExtra)
library(rnaturalearth)
library(viridis)
library(sf)
library(RColorBrewer)
library(rgeos)
library(gifski)
library(readxl)
library(gganimate)
library(ggrepel)
library(rworldmap)
```


# Background

LinkedIn is an illustrious website that helps professionals connect with one another. It is also a portal for people to display their skills as well as the path that their career has taken through the years. It contains a variety of information ranging from education, knowledge to checkpoints in their career.

Employers also use this platform for recruiting professionals. So it is a useful tool which is slowly becoming a necessity for people entering into the corporate world. Navigation and understanding crucial skills for their profession of choice and the location they would flourish goes a long way in crafting a successful career.


# Scope


## Information on Data

The World Bank Group - Linkedin Digital Data for Development^[@linkedin] attempts to harness LinkedIn data covering more than 100 countries. For the purpose of this report the following datasets will be accessed:

- Excel: Industry Skills Needs
- Excel: Talent Migration
- Excel: Employment Growth


# Rationale

The report will be charting the trends in LinkedIn across all fields. It will be delving into the kind of skills that are gaining or losing popularity across different verticals as well as what the top few must have skills are for all working professionals.

The other useful component for young professionals is what the migration trends are with respect to their skills and which place would give them space to learn and display their potential.

The final aspect but supremely important one is whether the global employment trends are conducive to their growth. Only upon knowing this aspect is it possible for them to decide whether migration is a good option or upskilling is 


# Research Questions


# Methodology


## Skills

## Talent Migration

## Employment Growth


# Analysis

# Conclusions

# Recommendations

# Limitations

# Bibliography
